//
//  CssColors.swift
//  Part of InterfaCSS - http://www.github.com/tolo/InterfaCSS
//
//  Copyright (c) Tobias Löfstrand, Leafnode AB.
//  License: MIT - http://www.github.com/tolo/InterfaCSS/blob/master/LICENSE
//

import UIKit

class CssColors {
  
  private static let nameToColor: [String: UIColor] = [
    // iOS colors
    "clear": .clear,
    "systemred": .systemRed,
    "systemgreen": .systemGreen,
    "systemblue": .systemBlue,
    "systemorange": .systemOrange,
    "systemyellow": .systemYellow,
    "systempink": .systemPink,
    "systempurple": .systemPurple,
    "systemteal": .systemTeal,
    //"systemindigo": .systemIndigo, // TODO: Only iOS13+
    
    "transparent": .clear,
    "black": UIColor.fromHexString("000000"),
    "silver": UIColor.fromHexString("c0c0c0"),
    "gray": UIColor.fromHexString("808080"),
    "white": UIColor.fromHexString("ffffff"),
    "maroon": UIColor.fromHexString("800000"),
    "red": UIColor.fromHexString("ff0000"),
    "purple": UIColor.fromHexString("800080"),
    "fuchsia": UIColor.fromHexString("ff00ff"),
    "green": UIColor.fromHexString("008000"),
    "lime": UIColor.fromHexString("00ff00"),
    "olive": UIColor.fromHexString("808000"),
    "yellow": UIColor.fromHexString("ffff00"),
    "navy": UIColor.fromHexString("000080"),
    "blue": UIColor.fromHexString("0000ff"),
    "teal": UIColor.fromHexString("008080"),
    "aqua": UIColor.fromHexString("00ffff"),
    "orange": UIColor.fromHexString("ffa500"),
    "aliceblue": UIColor.fromHexString("f0f8ff"),
    "antiquewhite": UIColor.fromHexString("faebd7"),
    "aquamarine": UIColor.fromHexString("7fffd4"),
    "azure": UIColor.fromHexString("f0ffff"),
    "beige": UIColor.fromHexString("f5f5dc"),
    "bisque": UIColor.fromHexString("ffe4c4"),
    "blanchedalmond": UIColor.fromHexString("ffebcd"),
    "blueviolet": UIColor.fromHexString("8a2be2"),
    "brown": UIColor.fromHexString("a52a2a"),
    "burlywood": UIColor.fromHexString("deb887"),
    "cadetblue": UIColor.fromHexString("5f9ea0"),
    "chartreuse": UIColor.fromHexString("7fff00"),
    "chocolate": UIColor.fromHexString("d2691e"),
    "coral": UIColor.fromHexString("ff7f50"),
    "cornflowerblue": UIColor.fromHexString("6495ed"),
    "cornsilk": UIColor.fromHexString("fff8dc"),
    "crimson": UIColor.fromHexString("dc143c"),
    "cyan": UIColor.fromHexString("00ffff"),
    "darkblue": UIColor.fromHexString("00008b"),
    "darkcyan": UIColor.fromHexString("008b8b"),
    "darkgoldenrod": UIColor.fromHexString("b8860b"),
    "darkgray": UIColor.fromHexString("a9a9a9"),
    "darkgreen": UIColor.fromHexString("006400"),
    "darkgrey": UIColor.fromHexString("a9a9a9"),
    "darkkhaki": UIColor.fromHexString("bdb76b"),
    "darkmagenta": UIColor.fromHexString("8b008b"),
    "darkolivegreen": UIColor.fromHexString("556b2f"),
    "darkorange": UIColor.fromHexString("ff8c00"),
    "darkorchid": UIColor.fromHexString("9932cc"),
    "darkred": UIColor.fromHexString("8b0000"),
    "darksalmon": UIColor.fromHexString("e9967a"),
    "darkseagreen": UIColor.fromHexString("8fbc8f"),
    "darkslateblue": UIColor.fromHexString("483d8b"),
    "darkslategray": UIColor.fromHexString("2f4f4f"),
    "darkslategrey": UIColor.fromHexString("2f4f4f"),
    "darkturquoise": UIColor.fromHexString("00ced1"),
    "darkviolet": UIColor.fromHexString("9400d3"),
    "deeppink": UIColor.fromHexString("ff1493"),
    "deepskyblue": UIColor.fromHexString("00bfff"),
    "dimgray": UIColor.fromHexString("696969"),
    "dimgrey": UIColor.fromHexString("696969"),
    "dodgerblue": UIColor.fromHexString("1e90ff"),
    "firebrick": UIColor.fromHexString("b22222"),
    "floralwhite": UIColor.fromHexString("fffaf0"),
    "forestgreen": UIColor.fromHexString("228b22"),
    "gainsboro": UIColor.fromHexString("dcdcdc"),
    "ghostwhite": UIColor.fromHexString("f8f8ff"),
    "gold": UIColor.fromHexString("ffd700"),
    "goldenrod": UIColor.fromHexString("daa520"),
    "greenyellow": UIColor.fromHexString("adff2f"),
    "grey": UIColor.fromHexString("808080"),
    "honeydew": UIColor.fromHexString("f0fff0"),
    "hotpink": UIColor.fromHexString("ff69b4"),
    "indianred": UIColor.fromHexString("cd5c5c"),
    "indigo": UIColor.fromHexString("4b0082"),
    "ivory": UIColor.fromHexString("fffff0"),
    "khaki": UIColor.fromHexString("f0e68c"),
    "lavender": UIColor.fromHexString("e6e6fa"),
    "lavenderblush": UIColor.fromHexString("fff0f5"),
    "lawngreen": UIColor.fromHexString("7cfc00"),
    "lemonchiffon": UIColor.fromHexString("fffacd"),
    "lightblue": UIColor.fromHexString("add8e6"),
    "lightcoral": UIColor.fromHexString("f08080"),
    "lightcyan": UIColor.fromHexString("e0ffff"),
    "lightgoldenrodyellow": UIColor.fromHexString("fafad2"),
    "lightgray": UIColor.fromHexString("d3d3d3"),
    "lightgreen": UIColor.fromHexString("90ee90"),
    "lightgrey": UIColor.fromHexString("d3d3d3"),
    "lightpink": UIColor.fromHexString("ffb6c1"),
    "lightsalmon": UIColor.fromHexString("ffa07a"),
    "lightseagreen": UIColor.fromHexString("20b2aa"),
    "lightskyblue": UIColor.fromHexString("87cefa"),
    "lightslategray": UIColor.fromHexString("778899"),
    "lightslategrey": UIColor.fromHexString("778899"),
    "lightsteelblue": UIColor.fromHexString("b0c4de"),
    "lightyellow": UIColor.fromHexString("ffffe0"),
    "limegreen": UIColor.fromHexString("32cd32"),
    "linen": UIColor.fromHexString("faf0e6"),
    "magenta": UIColor.fromHexString("ff00ff"),
    "mediumaquamarine": UIColor.fromHexString("66cdaa"),
    "mediumblue": UIColor.fromHexString("0000cd"),
    "mediumorchid": UIColor.fromHexString("ba55d3"),
    "mediumpurple": UIColor.fromHexString("9370db"),
    "mediumseagreen": UIColor.fromHexString("3cb371"),
    "mediumslateblue": UIColor.fromHexString("7b68ee"),
    "mediumspringgreen": UIColor.fromHexString("00fa9a"),
    "mediumturquoise": UIColor.fromHexString("48d1cc"),
    "mediumvioletred": UIColor.fromHexString("c71585"),
    "midnightblue": UIColor.fromHexString("191970"),
    "mintcream": UIColor.fromHexString("f5fffa"),
    "mistyrose": UIColor.fromHexString("ffe4e1"),
    "moccasin": UIColor.fromHexString("ffe4b5"),
    "navajowhite": UIColor.fromHexString("ffdead"),
    "oldlace": UIColor.fromHexString("fdf5e6"),
    "olivedrab": UIColor.fromHexString("6b8e23"),
    "orangered": UIColor.fromHexString("ff4500"),
    "orchid": UIColor.fromHexString("da70d6"),
    "palegoldenrod": UIColor.fromHexString("eee8aa"),
    "palegreen": UIColor.fromHexString("98fb98"),
    "paleturquoise": UIColor.fromHexString("afeeee"),
    "palevioletred": UIColor.fromHexString("db7093"),
    "papayawhip": UIColor.fromHexString("ffefd5"),
    "peachpuff": UIColor.fromHexString("ffdab9"),
    "peru": UIColor.fromHexString("cd853f"),
    "pink": UIColor.fromHexString("ffc0cb"),
    "plum": UIColor.fromHexString("dda0dd"),
    "powderblue": UIColor.fromHexString("b0e0e6"),
    "rosybrown": UIColor.fromHexString("bc8f8f"),
    "royalblue": UIColor.fromHexString("4169e1"),
    "saddlebrown": UIColor.fromHexString("8b4513"),
    "salmon": UIColor.fromHexString("fa8072"),
    "sandybrown": UIColor.fromHexString("f4a460"),
    "seagreen": UIColor.fromHexString("2e8b57"),
    "seashell": UIColor.fromHexString("fff5ee"),
    "sienna": UIColor.fromHexString("a0522d"),
    "skyblue": UIColor.fromHexString("87ceeb"),
    "slateblue": UIColor.fromHexString("6a5acd"),
    "slategray": UIColor.fromHexString("708090"),
    "slategrey": UIColor.fromHexString("708090"),
    "snow": UIColor.fromHexString("fffafa"),
    "springgreen": UIColor.fromHexString("00ff7f"),
    "steelblue": UIColor.fromHexString("4682b4"),
    "tan": UIColor.fromHexString("d2b48c"),
    "thistle": UIColor.fromHexString("d8bfd8"),
    "tomato": UIColor.fromHexString("ff6347"),
    "turquoise": UIColor.fromHexString("40e0d0"),
    "violet": UIColor.fromHexString("ee82ee"),
    "wheat": UIColor.fromHexString("f5deb3"),
    "whitesmoke": UIColor.fromHexString("f5f5f5"),
    "yellowgreen": UIColor.fromHexString("9acd32"),
    "rebeccapurple": UIColor.fromHexString("663399")
  ]
  
  static func color(forName name: String) -> UIColor? {
    return nameToColor[name]
  }
}
