source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

use_frameworks!

target 'FlexAndChill' do
    pod 'InterfaCSS', :path => '../../'
    pod 'InterfaCSS/Layout', :path => '../../'
end
